version: '3.0'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'socialSolutions_db'
    ports:
      - '3306:3306'
    volumes:
      - './my/custom:/etc/mysql/conf.d'
      - './my/own/datadir:/var/lib/mysql'
    restart: always

  web-app:
    build: .
    ports:
      - '5000:80'
    environment:
      MYSQL_CONNECTION_STR: 'Server=database; UserId=root; Password=123456; Database=socialSolutions_db'
    links:
      - database