version: '3.0'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'newDb_test'
      MYSQL_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - './my/custom:/etc/mysql/conf.d'
      - './my/own/datadir:/var/lib/mysql'

  web-app:
    build: .
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      MYSQL_CONNECTION_STR: 'Server=database; UserId=root; Password=123456; Database=newDb_test'
    links:
      - database